//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSoap1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cama", Namespace="http://schemas.datacontract.org/2004/07/RncciSolution.Models")]
    [System.SerializableAttribute()]
    public partial class Cama : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_camaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cod_unidade_fisicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_cama {
            get {
                return this.Cod_camaField;
            }
            set {
                if ((this.Cod_camaField.Equals(value) != true)) {
                    this.Cod_camaField = value;
                    this.RaisePropertyChanged("Cod_cama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod_unidade_fisica {
            get {
                return this.Cod_unidade_fisicaField;
            }
            set {
                if ((this.Cod_unidade_fisicaField.Equals(value) != true)) {
                    this.Cod_unidade_fisicaField = value;
                    this.RaisePropertyChanged("Cod_unidade_fisica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAtribuiCama")]
    public interface IAtribuiCama {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtribuiCama/GetCamaDisponivel", ReplyAction="http://tempuri.org/IAtribuiCama/GetCamaDisponivelResponse")]
        ClientSoap1.ServiceReference1.Cama[] GetCamaDisponivel(int cod_unidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtribuiCama/GetCamaDisponivel", ReplyAction="http://tempuri.org/IAtribuiCama/GetCamaDisponivelResponse")]
        System.Threading.Tasks.Task<ClientSoap1.ServiceReference1.Cama[]> GetCamaDisponivelAsync(int cod_unidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtribuiCama/AtribuiCamaUtente", ReplyAction="http://tempuri.org/IAtribuiCama/AtribuiCamaUtenteResponse")]
        bool AtribuiCamaUtente(int cod_cama, int cod_utente, System.DateTime dataSaida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtribuiCama/AtribuiCamaUtente", ReplyAction="http://tempuri.org/IAtribuiCama/AtribuiCamaUtenteResponse")]
        System.Threading.Tasks.Task<bool> AtribuiCamaUtenteAsync(int cod_cama, int cod_utente, System.DateTime dataSaida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAtribuiCamaChannel : ClientSoap1.ServiceReference1.IAtribuiCama, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtribuiCamaClient : System.ServiceModel.ClientBase<ClientSoap1.ServiceReference1.IAtribuiCama>, ClientSoap1.ServiceReference1.IAtribuiCama {
        
        public AtribuiCamaClient() {
        }
        
        public AtribuiCamaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtribuiCamaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtribuiCamaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtribuiCamaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientSoap1.ServiceReference1.Cama[] GetCamaDisponivel(int cod_unidade) {
            return base.Channel.GetCamaDisponivel(cod_unidade);
        }
        
        public System.Threading.Tasks.Task<ClientSoap1.ServiceReference1.Cama[]> GetCamaDisponivelAsync(int cod_unidade) {
            return base.Channel.GetCamaDisponivelAsync(cod_unidade);
        }
        
        public bool AtribuiCamaUtente(int cod_cama, int cod_utente, System.DateTime dataSaida) {
            return base.Channel.AtribuiCamaUtente(cod_cama, cod_utente, dataSaida);
        }
        
        public System.Threading.Tasks.Task<bool> AtribuiCamaUtenteAsync(int cod_cama, int cod_utente, System.DateTime dataSaida) {
            return base.Channel.AtribuiCamaUtenteAsync(cod_cama, cod_utente, dataSaida);
        }
    }
}
